"""added category and subcategory

Revision ID: 44ac125d1d60
Revises: 9dccd62f6e2c
Create Date: 2024-11-20 23:01:17.868469

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '44ac125d1d60'
down_revision: Union[str, None] = '9dccd62f6e2c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('subcategory_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'categories', ['subcategory_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'subcategory_id')
    # ### end Alembic commands ###
